name = "deepseek-chat-worker"
main = "src/index.ts"
compatibility_date = "2023-08-14"
compatibility_flags = ["nodejs_compat"]

# Custom domain configuration
[[routes]]
pattern = "api.zhimahu.work/*"
zone_name = "zhimahu.work"

[vars]
DEEPSEEK_API_URL = "https://api.deepseek.com/v1/chat/completions"

[env.production.vars]
ENVIRONMENT = "production"

[env.development.vars]
ENVIRONMENT = "development"

[[env.production.kv_namespaces]]
binding = "CHAT_HISTORY"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[[env.development.kv_namespaces]]
binding = "CHAT_HISTORY"
id = "your-dev-kv-namespace-id"
preview_id = "your-dev-preview-kv-namespace-id"