name = "deepseek-chat-worker"
main = "src/index.ts"
compatibility_date = "2023-08-14"
compatibility_flags = ["nodejs_compat"]

# Custom domain configuration
[[routes]]
pattern = "api.zhimahu.work/*"
zone_name = "zhimahu.work"

[vars]
DEEPSEEK_API_URL = "https://api.deepseek.com/v1/chat/completions"

# KV namespace binding - will be configured in Cloudflare Dashboard
[[kv_namespaces]]
binding = "CHAT_HISTORY"
id = ""
preview_id = ""