name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    name: Test Frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test --coverage --watchAll=false

      - name: Build frontend
        run: yarn build
        env:
          REACT_APP_WORKER_URL: https://api.zhimahu.work/graphql

  test-worker:
    runs-on: ubuntu-latest
    name: Test Worker

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: 'worker/yarn.lock'

      - name: Install dependencies
        working-directory: ./worker
        run: yarn install --frozen-lockfile

      - name: Type check
        working-directory: ./worker
        run: yarn tsc --noEmit

      - name: Build worker
        working-directory: ./worker
        run: yarn build