name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main
    paths:
      - 'worker/**'
      - '.github/workflows/deploy-worker.yml'
  pull_request:
    paths:
      - 'worker/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Worker to Cloudflare

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: 'worker/yarn.lock'

      - name: Install dependencies
        working-directory: ./worker
        run: yarn install --frozen-lockfile

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: 'worker'
          command: deploy

      - name: Notify deployment success
        if: success()
        run: echo "🚀 Worker deployed successfully to https://api.zhimahu.work"